#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start

#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Copy custom configuration file
cp /vagrant/default /etc/nginx/sites-available/

# Create symbolic link to configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
service nginx restart