#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend iconnects.tech
    timeout client  30000
    bind 0:80
    default_backend iconnects.tech_backend

backend iconnects.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 45817-web-01 100.25.196.128:80 check
    server 45817-web-02 54.237.118.39:80 check
EOT

sudo service haproxy restart
