#!/usr/bin/env bash

# Update system packages
apt-get update

# Install Nginx
apt-get install -y nginx

# Remove the default configuration file
rm /etc/nginx/sites-enabled/default

# Create a new default configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
service nginx restart
